// Generated from SimpleG.g4 by ANTLR 4.4

package org.antlr4gwt.demo.shared.grammar;
//This file had been generated by Antlr4.4 the desktop version

import org.antlr.v4.runtime.misc.NotNull;
import org.antlr.v4.runtime.tree.ParseTreeListener;

/**
 * This interface defines a complete listener for a parse tree produced by
 * {@link SimpleGParser}.
 */
public interface SimpleGListener extends ParseTreeListener {
	/**
	 * Enter a parse tree produced by {@link SimpleGParser#first_cell}.
	 * @param ctx the parse tree
	 */
	void enterFirst_cell(@NotNull SimpleGParser.First_cellContext ctx);
	/**
	 * Exit a parse tree produced by {@link SimpleGParser#first_cell}.
	 * @param ctx the parse tree
	 */
	void exitFirst_cell(@NotNull SimpleGParser.First_cellContext ctx);
	/**
	 * Enter a parse tree produced by {@link SimpleGParser#root}.
	 * @param ctx the parse tree
	 */
	void enterRoot(@NotNull SimpleGParser.RootContext ctx);
	/**
	 * Exit a parse tree produced by {@link SimpleGParser#root}.
	 * @param ctx the parse tree
	 */
	void exitRoot(@NotNull SimpleGParser.RootContext ctx);
	/**
	 * Enter a parse tree produced by {@link SimpleGParser#expr}.
	 * @param ctx the parse tree
	 */
	void enterExpr(@NotNull SimpleGParser.ExprContext ctx);
	/**
	 * Exit a parse tree produced by {@link SimpleGParser#expr}.
	 * @param ctx the parse tree
	 */
	void exitExpr(@NotNull SimpleGParser.ExprContext ctx);
	/**
	 * Enter a parse tree produced by {@link SimpleGParser#cell}.
	 * @param ctx the parse tree
	 */
	void enterCell(@NotNull SimpleGParser.CellContext ctx);
	/**
	 * Exit a parse tree produced by {@link SimpleGParser#cell}.
	 * @param ctx the parse tree
	 */
	void exitCell(@NotNull SimpleGParser.CellContext ctx);
}